glide COMMAND:
    @sed -i 's/axi/\/\/axi/g' main.go
    @sed -i 's/"xcl/\/\/"xcl/g' cmd/test-mcmc/main.go
    @sed -i 's/_ /\/\/_ /g' main.go
    git commit -am "glide"
    @glide {{ COMMAND }}
    @sed -i 's/\/\/axi/axi/g' main.go
    @sed -i 's/\/\/_ /_ /g' main.go
    @sed -i 's/\/\/"xcl/"xcl/g' cmd/test-mcmc/main.go

test:
    reco test run test-regression

check:
    reco check
