glide COMMAND:
    @sed -i.bk '/aximemory\|axiprotocol\|sdaccel/d' main.go
    @mv main.go.bk ../
    @glide {{ COMMAND }}
    @mv ../main.go.bk main.go

test:
    reco project set mcmc
    reco test run test-mcmc

check:
    reco check
